export function prvoPitanje() {
  return [
    "WWW - osnove (HTTP, HTML, URL)",
    "Web aplikacije",
    "Desktop vs mobilne vs web aplikacija",
    "Arhitektura Web aplikacija (dijagram, cloud)",
    "Klijent strana (tehnologije, izazovi)",
    "Server strana (tehnologije, izazovi)",
    "Protokoli (HTTP 1.0, 1.1, 2.0, Websocket)",
    "HTTP - opis, metode zahteva, poruke odgovora",
    "HTML 5, opste, struktura strane, semanticki elementi",
    "CSS, opste, box model, selektori",
    "Modeli klijent-server komunikacije",
    "Websocket protokol",
    "Prenos podataka sa klijenta na server",
    "AJAX",
    "CORS (primeri za same origin)",
    "Formati odgovora servera",
    "XML tehnologije (namespace, schema, xpath, xsl), obrada XML dokumenta (DOM, SAX)",
    "Poređenje XML i HTML, XML i JSON",
    "JSON",
    "Web server (arhitektura, tehnologije)",
    "ORM alati",
    "Raspoređivanje opterećenja servera",
    "Računarstvo u oblaku",
    "Serverless arhitektura",
    "Web servisi (RPC, SOAP, REST)",
    "RESTful servisi",
    "GraphQL",
    "SPA",
    "PWA",
    "Mikroservisi",
    "Virtualizacija",
    "Kontejnerizacija, Docker, compose",
    "Orkestracija kontejnera (Kubernetes, Docker Swarm)",
    "Web Assembly",
    "Blazor",
    "Blockchain",
  ];
}

export function drugoPitanje() {
  return [
    "Javascript (JS), opste",
    "JS tipovi (Primitivni, Objekti, null vs undefined)",
    "Promenljive",
    "Operatori poređenja, dodele (??, ??= )",
    "Funkcije, razlika izmedju deklaracije i izraza fje (FE)",
    "Hoisting – Podizanje fja",
    "Lambda fje",
    "Nizovi, ugradjene metode",
    "DOM, definicija i najcesce funkcije API-ja",
    "Closure i konteksti izvrsenja fja",
    "IIFE (+ klasa sa privatnim članovima)",
    "Objekat literali",
    "Prototipovi (+ Prototipski lanac)",
    "Klase preko prototipova (dodavanje metoda na prototip)",
    "ES6 Klase , nasleđivanje (i primer)",
    "ES6 Property članovi klase, prava pristupa (private, public)",
    "ES6 moduli",
    "Asihrono programiranje, Callback fje",
    "Event loop",
    "Promise, Async await",
    "JS operatori (spread, op dekonstrukcije, desktrukciona dodela)",
    "JS Strukture (Map vs Object)",
    "Proxy",
  ];
}

export function trecePitanje() {
  return [
    "Typescript",
    "TS interfejsi, aliasi, poređenje tipova",
    "Unija, spajanje tipova ( |, &)",
    "Typescript klase (+ primer)",
    "Enumeracije",
    "Typescript nasleđivanje (+ primer)",
    "Typescript šabloni (+ primer)",
    "Sužavanje tipova (+ typeof guard)",
    "Keyof operator",
    "Uslovni tipovi",
    "Mapirani tipovi",
    "Diskriminišuće unije, retrospektivno verziranje",
    "Uslužni tipovi (Partial, Omit, Pick)",
    "Potpisi funkcija (alias za potpis, višestruki potpis)",
  ];
}
